In [1]:
import pandas as bd

In [2]:
datos = bd.read_csv('INAH_detallado_2019.csv', encoding='latin-1')

In [3]:
datos

,Estado,Clave SIINAH,Siglas,Centro de trabajo,Año,Mes,Tipo de visitantes,Número de visitas,Nacionalidad
0,Aguascalientes,2300100.0,M.- M.H,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel básico,527,Nacional
1,Aguascalientes,2300100.0,M.- M.H,Museo Regional de Historia de Aguascalientes,2019,1,Entrada dominical,617,Nacional
2,Aguascalientes,2300100.0,M.- M.H,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,19,Extranjeros
3,Aguascalientes,2300100.0,M.- M.H,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel superior,188,Nacional
4,Aguascalientes,2300100.0,M.- M.H,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,80,Nacional
...,...,...,...,...,...,...,...,...,...
42674,Zacatecas,3110022.0,Z.A.,Z.A. de La Quemada con museo de sitio,2019,12,Exposiciones temporales con costo adicional,0,Extranjeros
42675,Zacatecas,3110022.0,Z.A.,Z.A. de La Quemada con museo de sitio,2019,12,Trabajadores INAH,0,Nacional
42676,Zacatecas,3110022.0,Z.A.,Z.A. de La Quemada con museo de sitio,2019,12,"Tercera edad, pensionados y jubilados",311,Nacional
42677,Zacatecas,3110022.0,Z.A.,Z.A. de La Quemada con museo de sitio,2019,12,Exposiciones temporales con costo adicional,0,Nacional
42678,Zacatecas,3110022.0,Z.A.,Z.A. de La Quemada con museo de sitio,2019,12,Entrada sin costo,0,Extranjeros

In [5]:
del datos['Siglas']

In [6]:
datos

,Estado,Clave SIINAH,Centro de trabajo,Año,Mes,Tipo de visitantes,Número de visitas,Nacionalidad
0,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel básico,527,Nacional
1,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Entrada dominical,617,Nacional
2,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,19,Extranjeros
3,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel superior,188,Nacional
4,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,80,Nacional
...,...,...,...,...,...,...,...,...
42674,Zacatecas,3110022.0,Z.A. de La Quemada con museo de sitio,2019,12,Exposiciones temporales con costo adicional,0,Extranjeros
42675,Zacatecas,3110022.0,Z.A. de La Quemada con museo de sitio,2019,12,Trabajadores INAH,0,Nacional
42676,Zacatecas,3110022.0,Z.A. de La Quemada con museo de sitio,2019,12,"Tercera edad, pensionados y jubilados",311,Nacional
42677,Zacatecas,3110022.0,Z.A. de La Quemada con museo de sitio,2019,12,Exposiciones temporales con costo adicional,0,Nacional
42678,Zacatecas,3110022.0,Z.A. de La Quemada con museo de sitio,2019,12,Entrada sin costo,0,Extranjeros

In [8]:
datos.Año.describe()

count    42679.0
mean      2019.0
std          0.0
min       2019.0
25%       2019.0
50%       2019.0
75%       2019.0
max       2019.0
Name: Año, dtype: float64

In [9]:
datos.Mes.describe()

count    42679.000000
mean         6.521779
std          3.455479
min          1.000000
25%          4.000000
50%          7.000000
75%         10.000000
max         12.000000
Name: Mes, dtype: float64

In [10]:
datos.Estado.describe()

count                42679
unique                  32
top       Estado de México
freq                  4056
Name: Estado, dtype: object

In [11]:
datos['Estado']

0        Aguascalientes
1        Aguascalientes
2        Aguascalientes
3        Aguascalientes
4        Aguascalientes
              ...
42674         Zacatecas
42675         Zacatecas
42676         Zacatecas
42677         Zacatecas
42678         Zacatecas
Name: Estado, Length: 42679, dtype: object

In [12]:
datos['Estado', datos.Año.describe()]

TypeError: '('Estado', count    42679.0
mean      2019.0
std          0.0
min       2019.0
25%       2019.0
50%       2019.0
75%       2019.0
max       2019.0
Name: Año, dtype: float64)' is an invalid key

KeyError: 'Aguascalientes'

In [14]:
datos['Estado'=='Aguascalientes']

KeyError: False

In [15]:
datos[datos['Estado']=='Aguascalientes']

,Estado,Clave SIINAH,Centro de trabajo,Año,Mes,Tipo de visitantes,Número de visitas,Nacionalidad
0,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel básico,527,Nacional
1,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Entrada dominical,617,Nacional
2,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,19,Extranjeros
3,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel superior,188,Nacional
4,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,80,Nacional
...,...,...,...,...,...,...,...,...
151,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Exposiciones temporales con costo adicional,0,Extranjeros
152,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Trabajadores INAH,0,Nacional
153,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,"Tercera edad, pensionados y jubilados",53,Nacional
154,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Exposiciones temporales con costo adicional,0,Nacional
155,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Entrada sin costo,2,Extranjeros

In [16]:
datos[datos['Estado']=='Aguascalientes'].describe()

       Clave SIINAH     Año        Mes
count         156.0   156.0  156.00000
mean      2300100.0  2019.0    6.50000
std             0.0     0.0    3.46317
min       2300100.0  2019.0    1.00000
25%       2300100.0  2019.0    3.75000
50%       2300100.0  2019.0    6.50000
75%       2300100.0  2019.0    9.25000
max       2300100.0  2019.0   12.00000

In [17]:
datos.dropna['Clave SIINAH'].

TypeError: 'method' object is not subscriptable

In [18]:
datos[datos['Estado']=='Aguascalientes'].describe()

       Clave SIINAH     Año        Mes
count         156.0   156.0  156.00000
mean      2300100.0  2019.0    6.50000
std             0.0     0.0    3.46317
min       2300100.0  2019.0    1.00000
25%       2300100.0  2019.0    3.75000
50%       2300100.0  2019.0    6.50000
75%       2300100.0  2019.0    9.25000
max       2300100.0  2019.0   12.00000

In [20]:
datos.drop(['Clave SIINAH'], axis=1 [datos['Estado']=='Aguascalientes'].describe())

TypeError: 'int' object is not subscriptable

In [23]:
datos[datos['Estado']=='Aguascalientes', 'Mes']

TypeError: '(0         True
1         True
2         True
3         True
4         True
         ...
42674    False
42675    False
42676    False
42677    False
42678    False
Name: Estado, Length: 42679, dtype: bool, 'Mes')' is an invalid key

In [24]:
datos['Mes']

0         1
1         1
2         1
3         1
4         1
         ..
42674    12
42675    12
42676    12
42677    12
42678    12
Name: Mes, Length: 42679, dtype: int64

,Estado,Clave SIINAH,Centro de trabajo,Año,Mes,Tipo de visitantes,Número de visitas,Nacionalidad
0,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel básico,527,Nacional
1,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Entrada dominical,617,Nacional
2,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,19,Extranjeros
3,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel superior,188,Nacional
4,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,80,Nacional
...,...,...,...,...,...,...,...,...
151,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Exposiciones temporales con costo adicional,0,Extranjeros
152,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Trabajadores INAH,0,Nacional
153,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,"Tercera edad, pensionados y jubilados",53,Nacional
154,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Exposiciones temporales con costo adicional,0,Nacional
155,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Entrada sin costo,2,Extranjeros

In [28]:
datos['Mes']

0         1
1         1
2         1
3         1
4         1
         ..
42674    12
42675    12
42676    12
42677    12
42678    12
Name: Mes, Length: 42679, dtype: int64

In [31]:
datos['Estado']

0        Aguascalientes
1        Aguascalientes
2        Aguascalientes
3        Aguascalientes
4        Aguascalientes
              ...
42674         Zacatecas
42675         Zacatecas
42676         Zacatecas
42677         Zacatecas
42678         Zacatecas
Name: Estado, Length: 42679, dtype: object

In [32]:

datos[datos['Estado']=='Aguascalientes']

,Estado,Clave SIINAH,Centro de trabajo,Año,Mes,Tipo de visitantes,Número de visitas,Nacionalidad
0,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel básico,527,Nacional
1,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Entrada dominical,617,Nacional
2,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,19,Extranjeros
3,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel superior,188,Nacional
4,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,80,Nacional
...,...,...,...,...,...,...,...,...
151,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Exposiciones temporales con costo adicional,0,Extranjeros
152,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Trabajadores INAH,0,Nacional
153,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,"Tercera edad, pensionados y jubilados",53,Nacional
154,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Exposiciones temporales con costo adicional,0,Nacional
155,Aguascalientes,2300100.0,Museo Regional de Historia de Aguascalientes,2019,12,Entrada sin costo,2,Extranjeros

In [33]:
ag = datos[datos['Estado']=='Aguascalientes']

In [37]:
ag

,Estado,Centro de trabajo,Año,Mes,Tipo de visitantes,Número de visitas,Nacionalidad
0,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel básico,527,Nacional
1,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,1,Entrada dominical,617,Nacional
2,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,19,Extranjeros
3,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel superior,188,Nacional
4,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,80,Nacional
...,...,...,...,...,...,...,...
151,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,12,Exposiciones temporales con costo adicional,0,Extranjeros
152,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,12,Trabajadores INAH,0,Nacional
153,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,12,"Tercera edad, pensionados y jubilados",53,Nacional
154,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,12,Exposiciones temporales con costo adicional,0,Nacional
155,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,12,Entrada sin costo,2,Extranjeros

In [39]:
ag['Mes']

0       1
1       1
2       1
3       1
4       1
       ..
151    12
152    12
153    12
154    12
155    12
Name: Mes, Length: 156, dtype: int64

In [40]:
ag

,Estado,Centro de trabajo,Año,Mes,Tipo de visitantes,Número de visitas,Nacionalidad
0,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel básico,527,Nacional
1,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,1,Entrada dominical,617,Nacional
2,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,19,Extranjeros
3,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,1,Estudiantes nivel superior,188,Nacional
4,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,1,Boleto pagado,80,Nacional
...,...,...,...,...,...,...,...
151,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,12,Exposiciones temporales con costo adicional,0,Extranjeros
152,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,12,Trabajadores INAH,0,Nacional
153,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,12,"Tercera edad, pensionados y jubilados",53,Nacional
154,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,12,Exposiciones temporales con costo adicional,0,Nacional
155,Aguascalientes,Museo Regional de Historia de Aguascalientes,2019,12,Entrada sin costo,2,Extranjeros

In [41]:
ag['Número de visitas']

0      527
1      617
2       19
3      188
4       80
      ...
151      0
152      0
153     53
154      0
155      2
Name: Número de visitas, Length: 156, dtype: object

In [45]:
datos['Número de visitas'].describe()

count     42679
unique     3307
top           0
freq      20534
Name: Número de visitas, dtype: object

In [46]:
ag['Número de visitas'].describe()

count     156
unique     97
top         0
freq       37
Name: Número de visitas, dtype: object

In [47]:
ag['Número de visitas']

0      527
1      617
2       19
3      188
4       80
      ...
151      0
152      0
153     53
154      0
155      2
Name: Número de visitas, Length: 156, dtype: object

In [48]:
ag['Número de visitas'].describe()

count     156
unique     97
top         0
freq       37
Name: Número de visitas, dtype: object

In [51]:
ag['Número de visitas'].infer_objects()

0      527
1      617
2       19
3      188
4       80
      ...
151      0
152      0
153     53
154      0
155      2
Name: Número de visitas, Length: 156, dtype: object

In [62]:
ag['Número de visitas'].to_numeric(s, downcast='integer')

AttributeError: 'Series' object has no attribute 'to_numeric'

In [63]:
ag.to_numeric(s, downcast='integer')

AttributeError: 'DataFrame' object has no attribute 'to_numeric'

In [66]:
ag.astype(int)

ValueError: invalid literal for int() with base 10: 'Aguascalientes'

In [68]:
ag['Número de visitas'].astype(int)

ValueError: invalid literal for int() with base 10: '1,342'

ValueError: could not convert string to float: '1,342'